### PR TITLE
Using npx to invoke browserify.

### PR DESCRIPTION
**Pull request by jimbojw**
This ensures that the local, project-specific version of browserify is used and removes the need for globally installed browserify.

### CODE REVIEW

**Comment by jimbojw** [comment]
Travis build appears to have failed for reasons unrelated to this change:

```
> seedpicker@1.0.0 test:cucumber /home/travis/build/merland/seedpicker
> cucumber-js --require cucumber.conf.js --require step_definitions --format node_modules/cucumber-pretty

- Connecting to localhost on port 9515...

⚠ Error connecting to localhost on port 9515.
VError: a BeforeAll hook errored, process exiting: cucumber.conf.js:6: An error occurred while retrieving a new session: "session not created: This version of ChromeDriver only supports Chrome version 85"
    at /home/travis/build/merland/seedpicker/node_modules/cucumber/lib/runtime/index.js:60:15
caused by: Error: An error occurred while retrieving a new session: "session not created: This version of ChromeDriver only supports Chrome version 85"
    at JsonWireProtocol.handleSessionCreateError (/home/travis/build/merland/seedpicker/node_modules/nightwatch/lib/transport/transport.js:103:15)
    at HttpRequest.<anonymous> (/home/travis/build/merland/seedpicker/node_modules/nightwatch/lib/transport/transport.js:168:16)
    at HttpRequest.emit (events.js:209:13)
    at HttpResponse.<anonymous> (/home/travis/build/merland/seedpicker/node_modules/nightwatch/lib/http/request.js:142:19)
    at HttpResponse.emit (events.js:209:13)
    at IncomingMessage.<anonymous> (/home/travis/build/merland/seedpicker/node_modules/nightwatch/lib/http/response.js:58:14)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Root cause seems to be "This version of ChromeDriver only supports Chrome version 85"

**Comment by merland** [comment]
@jimbojw Thanks for this contribution, very appreciated! Looks like a good change.

Did you try a clean build after the change? (e.g. using ```rm -rf node_modules; ./build.sh```). I just did but I got some errors. I think my node environment may need some fixing though... I haven't worked on SeedPicker for a while. 

I'll try to look into the Travis problem when I find some time. Thanks for noticing.

**Comment by jimbojw** [comment]
> Did you try a clean build after the change? (e.g. using `rm -rf node_modules; ./build.sh`).

Yes, just did it now and it's working for me. The `bundle.js` that my build produces is slightly different than the checked-in version due to divergence in the upstream dependency on `elliptic` (checked-in bundle has v6.4.0, mine shows v6.5.3).

**Comment by jimbojw** [comment]
Updated to incorporate master branch.

**Pull request merged**
